name: Deploy to AWS

on:
  push:
    branches:
      - main  # Run only when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- FRONTEND BUILD ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and Build Frontend
        working-directory: ./client
        run: |
          npm ci
          npm run build

      # --- DEPLOY FRONTEND TO S3 ---
      - name: Deploy to S3
          uses: jakejarvis/s3-sync-action@v0.5.1
            with:
            args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: 'client/dist

      # --- INVALIDATE CLOUDFRONT CACHE ---
      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ env.DISTRIBUTION_ID }}
          aws-region: ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # --- DEPLOY BACKEND (LAMBDA) ---
      - name: Zip backend for Lambda
        run: |
          cd server
          zip -r ../lambda.zip .

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name famtree-lambda \
            --zip-file fileb://lambda.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

