name: Deploy Serverless App (S3 + Lambda)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1                # change if your S3/Lambda are in another region
      S3_BUCKET: ftm1-s3-eu       # e.g. famtree-bucket
      DISTRIBUTION_ID: EGHJFIL6SA7PK  # e.g. E1ABCDXYZ
      LAMBDA_NAME: ft1-backend-lambda          # your deployed Lambda function name

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- FRONTEND ----------
      - name: Build frontend
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ env.S3_BUCKET }}
          region: ${{ env.AWS_REGION }}
          source: client/dist
          delete: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront cache
        uses: awact/cloudfront-action@v1.3
        with:
          distribution-id: ${{ env.DISTRIBUTION_ID }}
          aws-region: ${{ env.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # ---------- BACKEND ----------
      - name: Zip backend
        run: |
          cd server
          zip -r ../lambda.zip . -x "node_modules/*" "*.env" ".history/*" ".git/*"

      - name: Deploy to Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          function_name: ${{ env.LAMBDA_NAME }}
          zip_file: lambda.zip

